/*
 * Ergo Explorer API v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ergolui.ergotipperbackend.explorer.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * NetworkState
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-05T14:07:15.709Z[GMT]")
public class NetworkState {
  @SerializedName("lastBlockId")
  private String lastBlockId = null;

  @SerializedName("height")
  private Integer height = null;

  @SerializedName("maxBoxGix")
  private Long maxBoxGix = null;

  @SerializedName("maxTxGix")
  private Long maxTxGix = null;

  @SerializedName("params")
  private EpochParameters params = null;

  public NetworkState lastBlockId(String lastBlockId) {
    this.lastBlockId = lastBlockId;
    return this;
  }

   /**
   * Modifier ID
   * @return lastBlockId
  **/
  @Schema(required = true, description = "Modifier ID")
  public String getLastBlockId() {
    return lastBlockId;
  }

  public void setLastBlockId(String lastBlockId) {
    this.lastBlockId = lastBlockId;
  }

  public NetworkState height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @Schema(required = true, description = "")
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public NetworkState maxBoxGix(Long maxBoxGix) {
    this.maxBoxGix = maxBoxGix;
    return this;
  }

   /**
   * Get maxBoxGix
   * @return maxBoxGix
  **/
  @Schema(required = true, description = "")
  public Long getMaxBoxGix() {
    return maxBoxGix;
  }

  public void setMaxBoxGix(Long maxBoxGix) {
    this.maxBoxGix = maxBoxGix;
  }

  public NetworkState maxTxGix(Long maxTxGix) {
    this.maxTxGix = maxTxGix;
    return this;
  }

   /**
   * Get maxTxGix
   * @return maxTxGix
  **/
  @Schema(required = true, description = "")
  public Long getMaxTxGix() {
    return maxTxGix;
  }

  public void setMaxTxGix(Long maxTxGix) {
    this.maxTxGix = maxTxGix;
  }

  public NetworkState params(EpochParameters params) {
    this.params = params;
    return this;
  }

   /**
   * Get params
   * @return params
  **/
  @Schema(required = true, description = "")
  public EpochParameters getParams() {
    return params;
  }

  public void setParams(EpochParameters params) {
    this.params = params;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkState networkState = (NetworkState) o;
    return Objects.equals(this.lastBlockId, networkState.lastBlockId) &&
        Objects.equals(this.height, networkState.height) &&
        Objects.equals(this.maxBoxGix, networkState.maxBoxGix) &&
        Objects.equals(this.maxTxGix, networkState.maxTxGix) &&
        Objects.equals(this.params, networkState.params);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastBlockId, height, maxBoxGix, maxTxGix, params);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkState {\n");
    
    sb.append("    lastBlockId: ").append(toIndentedString(lastBlockId)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    maxBoxGix: ").append(toIndentedString(maxBoxGix)).append("\n");
    sb.append("    maxTxGix: ").append(toIndentedString(maxTxGix)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
