/*
 * Ergo Explorer API v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ergolui.ergotipperbackend.explorer.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * UOutputInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-05T14:07:15.709Z[GMT]")
public class UOutputInfo {
  @SerializedName("boxId")
  private String boxId = null;

  @SerializedName("transactionId")
  private String transactionId = null;

  @SerializedName("value")
  private Long value = null;

  @SerializedName("index")
  private Integer index = null;

  @SerializedName("creationHeight")
  private Integer creationHeight = null;

  @SerializedName("ergoTree")
  private String ergoTree = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("assets")
  private List<AssetInstanceInfo> assets = null;

  @SerializedName("additionalRegisters")
  private AdditionalRegisters additionalRegisters = null;

  @SerializedName("spentTransactionId")
  private String spentTransactionId = null;

  public UOutputInfo boxId(String boxId) {
    this.boxId = boxId;
    return this;
  }

   /**
   * Id of the box
   * @return boxId
  **/
  @Schema(required = true, description = "Id of the box")
  public String getBoxId() {
    return boxId;
  }

  public void setBoxId(String boxId) {
    this.boxId = boxId;
  }

  public UOutputInfo transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Id of the transaction that created the box
   * @return transactionId
  **/
  @Schema(required = true, description = "Id of the transaction that created the box")
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public UOutputInfo value(Long value) {
    this.value = value;
    return this;
  }

   /**
   * Value of the box in nanoERG
   * @return value
  **/
  @Schema(required = true, description = "Value of the box in nanoERG")
  public Long getValue() {
    return value;
  }

  public void setValue(Long value) {
    this.value = value;
  }

  public UOutputInfo index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Index of the output in a transaction
   * @return index
  **/
  @Schema(required = true, description = "Index of the output in a transaction")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public UOutputInfo creationHeight(Integer creationHeight) {
    this.creationHeight = creationHeight;
    return this;
  }

   /**
   * Height at which the box was created
   * @return creationHeight
  **/
  @Schema(required = true, description = "Height at which the box was created")
  public Integer getCreationHeight() {
    return creationHeight;
  }

  public void setCreationHeight(Integer creationHeight) {
    this.creationHeight = creationHeight;
  }

  public UOutputInfo ergoTree(String ergoTree) {
    this.ergoTree = ergoTree;
    return this;
  }

   /**
   * Serialized ergo tree
   * @return ergoTree
  **/
  @Schema(required = true, description = "Serialized ergo tree")
  public String getErgoTree() {
    return ergoTree;
  }

  public void setErgoTree(String ergoTree) {
    this.ergoTree = ergoTree;
  }

  public UOutputInfo address(String address) {
    this.address = address;
    return this;
  }

   /**
   * An address derived from ergo tree
   * @return address
  **/
  @Schema(required = true, description = "An address derived from ergo tree")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public UOutputInfo assets(List<AssetInstanceInfo> assets) {
    this.assets = assets;
    return this;
  }

  public UOutputInfo addAssetsItem(AssetInstanceInfo assetsItem) {
    if (this.assets == null) {
      this.assets = new ArrayList<AssetInstanceInfo>();
    }
    this.assets.add(assetsItem);
    return this;
  }

   /**
   * Get assets
   * @return assets
  **/
  @Schema(description = "")
  public List<AssetInstanceInfo> getAssets() {
    return assets;
  }

  public void setAssets(List<AssetInstanceInfo> assets) {
    this.assets = assets;
  }

  public UOutputInfo additionalRegisters(AdditionalRegisters additionalRegisters) {
    this.additionalRegisters = additionalRegisters;
    return this;
  }

   /**
   * Get additionalRegisters
   * @return additionalRegisters
  **/
  @Schema(required = true, description = "")
  public AdditionalRegisters getAdditionalRegisters() {
    return additionalRegisters;
  }

  public void setAdditionalRegisters(AdditionalRegisters additionalRegisters) {
    this.additionalRegisters = additionalRegisters;
  }

  public UOutputInfo spentTransactionId(String spentTransactionId) {
    this.spentTransactionId = spentTransactionId;
    return this;
  }

   /**
   * Id of the transaction this output was spent by
   * @return spentTransactionId
  **/
  @Schema(description = "Id of the transaction this output was spent by")
  public String getSpentTransactionId() {
    return spentTransactionId;
  }

  public void setSpentTransactionId(String spentTransactionId) {
    this.spentTransactionId = spentTransactionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UOutputInfo uoutputInfo = (UOutputInfo) o;
    return Objects.equals(this.boxId, uoutputInfo.boxId) &&
        Objects.equals(this.transactionId, uoutputInfo.transactionId) &&
        Objects.equals(this.value, uoutputInfo.value) &&
        Objects.equals(this.index, uoutputInfo.index) &&
        Objects.equals(this.creationHeight, uoutputInfo.creationHeight) &&
        Objects.equals(this.ergoTree, uoutputInfo.ergoTree) &&
        Objects.equals(this.address, uoutputInfo.address) &&
        Objects.equals(this.assets, uoutputInfo.assets) &&
        Objects.equals(this.additionalRegisters, uoutputInfo.additionalRegisters) &&
        Objects.equals(this.spentTransactionId, uoutputInfo.spentTransactionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(boxId, transactionId, value, index, creationHeight, ergoTree, address, assets, additionalRegisters, spentTransactionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UOutputInfo {\n");
    
    sb.append("    boxId: ").append(toIndentedString(boxId)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    creationHeight: ").append(toIndentedString(creationHeight)).append("\n");
    sb.append("    ergoTree: ").append(toIndentedString(ergoTree)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    assets: ").append(toIndentedString(assets)).append("\n");
    sb.append("    additionalRegisters: ").append(toIndentedString(additionalRegisters)).append("\n");
    sb.append("    spentTransactionId: ").append(toIndentedString(spentTransactionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
