/*
 * Ergo Explorer API v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ergolui.ergotipperbackend.explorer.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * UTransactionInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-05T14:07:15.709Z[GMT]")
public class UTransactionInfo {
  @SerializedName("id")
  private String id = null;

  @SerializedName("creationTimestamp")
  private Long creationTimestamp = null;

  @SerializedName("inputs")
  private List<UInputInfo> inputs = null;

  @SerializedName("dataInputs")
  private List<UDataInputInfo> dataInputs = null;

  @SerializedName("outputs")
  private List<UOutputInfo> outputs = null;

  @SerializedName("size")
  private Integer size = null;

  public UTransactionInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Transaction ID
   * @return id
  **/
  @Schema(required = true, description = "Transaction ID")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public UTransactionInfo creationTimestamp(Long creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
    return this;
  }

   /**
   * Timestamp the transaction got into the network
   * @return creationTimestamp
  **/
  @Schema(required = true, description = "Timestamp the transaction got into the network")
  public Long getCreationTimestamp() {
    return creationTimestamp;
  }

  public void setCreationTimestamp(Long creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
  }

  public UTransactionInfo inputs(List<UInputInfo> inputs) {
    this.inputs = inputs;
    return this;
  }

  public UTransactionInfo addInputsItem(UInputInfo inputsItem) {
    if (this.inputs == null) {
      this.inputs = new ArrayList<UInputInfo>();
    }
    this.inputs.add(inputsItem);
    return this;
  }

   /**
   * Get inputs
   * @return inputs
  **/
  @Schema(description = "")
  public List<UInputInfo> getInputs() {
    return inputs;
  }

  public void setInputs(List<UInputInfo> inputs) {
    this.inputs = inputs;
  }

  public UTransactionInfo dataInputs(List<UDataInputInfo> dataInputs) {
    this.dataInputs = dataInputs;
    return this;
  }

  public UTransactionInfo addDataInputsItem(UDataInputInfo dataInputsItem) {
    if (this.dataInputs == null) {
      this.dataInputs = new ArrayList<UDataInputInfo>();
    }
    this.dataInputs.add(dataInputsItem);
    return this;
  }

   /**
   * Get dataInputs
   * @return dataInputs
  **/
  @Schema(description = "")
  public List<UDataInputInfo> getDataInputs() {
    return dataInputs;
  }

  public void setDataInputs(List<UDataInputInfo> dataInputs) {
    this.dataInputs = dataInputs;
  }

  public UTransactionInfo outputs(List<UOutputInfo> outputs) {
    this.outputs = outputs;
    return this;
  }

  public UTransactionInfo addOutputsItem(UOutputInfo outputsItem) {
    if (this.outputs == null) {
      this.outputs = new ArrayList<UOutputInfo>();
    }
    this.outputs.add(outputsItem);
    return this;
  }

   /**
   * Get outputs
   * @return outputs
  **/
  @Schema(description = "")
  public List<UOutputInfo> getOutputs() {
    return outputs;
  }

  public void setOutputs(List<UOutputInfo> outputs) {
    this.outputs = outputs;
  }

  public UTransactionInfo size(Integer size) {
    this.size = size;
    return this;
  }

   /**
   * Transaction size in bytes
   * @return size
  **/
  @Schema(required = true, description = "Transaction size in bytes")
  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UTransactionInfo utransactionInfo = (UTransactionInfo) o;
    return Objects.equals(this.id, utransactionInfo.id) &&
        Objects.equals(this.creationTimestamp, utransactionInfo.creationTimestamp) &&
        Objects.equals(this.inputs, utransactionInfo.inputs) &&
        Objects.equals(this.dataInputs, utransactionInfo.dataInputs) &&
        Objects.equals(this.outputs, utransactionInfo.outputs) &&
        Objects.equals(this.size, utransactionInfo.size);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, creationTimestamp, inputs, dataInputs, outputs, size);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UTransactionInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    creationTimestamp: ").append(toIndentedString(creationTimestamp)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    dataInputs: ").append(toIndentedString(dataInputs)).append("\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
