services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 0.0.0.0:5433:5432
  ergotipperbackend:
    build: .
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ERGOTIPPERBACKEND_SEED_SALT: ${ERGOTIPPERBACKEND_SEED_SALT}
    ports:
      - 0.0.0.0:8088:8080
volumes:
  postgres-data:
